export const PRODUCT = Object.freeze({
  id: 'magnetus_iii',
  name: 'Magnetus III',
  subtitle: 'Recupere sua Presença Masculina em 15 Dias',
  canonicalName: 'Magnetus III — Presença Masculina, Confiança e Postura em 15 Dias',
  promise: 'Identifique e ajuste os sinais que fazem a ansiedade falar antes de você — para sustentar presença, postura e comunicação com mais calma e firmeza em 15 dias.',
  format: '2 materiais digitais em PDF',
  bonusName: 'Antídoto do Antivalor',
  guaranteeDays: 7,
  checkoutUrl: 'https://pay.kiwify.com.br/TX2Ao2R',
  price: 79.9,
  priceLabel: 'R$ 79,90',
  installmentLabel: '6x de R$ 13,32',
  currency: 'BRL',
});
