export const PRODUCT = Object.freeze({
  id: 'magnetus_iii',
  name: 'Magnetus III',
  subtitle: 'Presença Masculina, Confiança e Postura em 15 Dias',
  canonicalName: 'Magnetus III — Presença Masculina, Confiança e Postura em 15 Dias',
  promise: 'Desenvolva presença masculina, confiança, postura e comunicação em 15 dias, sem parecer ansioso, carente ou inseguro.',
  format: '2 materiais digitais em PDF',
  bonusName: 'Antídoto do Antivalor',
  guaranteeDays: 7,
  checkoutUrl: 'https://pay.kiwify.com.br/TX2Ao2R',
  price: 79.9,
  priceLabel: 'R$ 79,90',
  installmentLabel: '6x de R$ 13,32',
  currency: 'BRL',
});